language: python
before_install:
  - sudo apt-get update -qq
  - sudo apt-get install -y python-lxml python-pip
  # here we don't use the travis virtualenv because that
  # causes us to install lxml again below, doubling the build time
  # when it compiles the native modules from source
  - deactivate
install:
 - gem install kramdown-rfc2629
 - sudo pip install xml2rfc
script: make ghpages
env:
  global:
  - secure: UdjatJt8TD2I8NRm5RJB0GCN4pt/Ba+BIYnUTe4ejF8bBrsq8eT3X9uGfsCceSTCb93NXgsAlytlvauYEtsWG54wgs7Jr9Q1Svc4KlrBLLwHsaKEt7UQRQtG8G+d56ZpDOvR8voh0RW/vGAQsDUYDdh3QrNAFdUH4Pq6T0MtxCw=
