language: python
install:
 - gem install kramdown-rfc2629
 - pip install xml2rfc
script: make ghpages
env:
  global:
  - secure: UdjatJt8TD2I8NRm5RJB0GCN4pt/Ba+BIYnUTe4ejF8bBrsq8eT3X9uGfsCceSTCb93NXgsAlytlvauYEtsWG54wgs7Jr9Q1Svc4KlrBLLwHsaKEt7UQRQtG8G+d56ZpDOvR8voh0RW/vGAQsDUYDdh3QrNAFdUH4Pq6T0MtxCw=
